version: "3.8"

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "80:80"
        volumes:
            - ./src:/var/www/html
            - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./config/fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf
        depends_on:
            - php

    php:
        image: php:8.1-fpm
        volumes:
            - ./src:/var/www/html
